# Generated by Django 3.2.7 on 2021-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_account',
            fields=[
                ('cus_userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cus_fullname', models.CharField(max_length=100)),
                ('cus_email', models.CharField(max_length=100)),
                ('cus_pass', models.CharField(max_length=50)),
                ('cus_phone', models.CharField(max_length=11)),
            ],
        ),
    ]
