# Generated by Django 3.2.7 on 2021-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_account',
            name='cus_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
