# Generated by Django 3.2.7 on 2021-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_account_cus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_account',
            name='cus_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
