# Generated by Django 3.2.7 on 2021-12-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefAccount',
            fields=[
                ('chef_userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('chef_fullname', models.CharField(max_length=100)),
                ('chef_email', models.CharField(max_length=100)),
                ('chef_password', models.CharField(max_length=10000)),
                ('chef_phone', models.CharField(max_length=11)),
            ],
        ),
    ]
