# Generated by Django 3.2.7 on 2021-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefaccount',
            name='shift',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
