# Generated by Django 3.2.7 on 2021-11-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='quantity',
            new_name='serving_quantity',
        ),
        migrations.AddField(
            model_name='food_item',
            name='food_catagory',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Chicken', 'Chicken'), ('Drinks', 'Drinks'), ('Sandwich', 'Sandwich'), ('Cake', 'Cake'), ('Donut', 'Donut'), ('Fry', 'Fry')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food_item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
