# Generated by Django 3.2.7 on 2021-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager_account',
            fields=[
                ('man_userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('man_fullname', models.CharField(max_length=100)),
                ('man_email', models.CharField(max_length=100)),
                ('man_pass', models.CharField(max_length=50)),
                ('man_phone', models.CharField(max_length=11)),
            ],
        ),
    ]
