# Generated by Django 3.2.7 on 2021-12-08 07:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_manager_account_man_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='Active', max_length=20)),
                ('total', models.FloatField()),
            ],
        ),
    ]
