# Generated by Django 3.2.7 on 2021-12-08 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='product_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
